package com.coursemanagerfx.logic.basic.event;

public enum TypeTag {
    SESSIYA, SFP, SK_KG_KV, ZAOHOCHENNYA, STYAGNENNYA, SEKRETNIKI,
    REDKOLEGIYA, JURNALISTI, SPORTORGI, NAUKA, SERTIFICATI, ZMAGANNYA,
    VOLONTERI, GROMAD_JITTYA, DODAT_BAL
}